language: elixir

deploy:
  provider: heroku
  app: secret-oasis-72243
  api_key:
    secure: PsHVor78mtls700HX4Hg06Nwmft8MLBm5+bpwiIOWwOYo9Rc5u6B2rtOsP8w+EjA2/VCAVcVXHDuM1xT+IU+pO1U1gCt1GRU+5GCORiR6+Jn9Q3sQ0G7X6sVC/htthNkLzTjDcoh7O/+TqRyOXiqdp7v+rTNFQKrjpLzLztYUqoHcVyZjThsoY+f/3+jVtHiDfPLROVb5Px1ijDvhtrUjS5UmoqGJDLoc9K7M+FnN1FshpghaUdjvHRjNd8admTQWzwS45cdudOPONFoLLwpUeTIztlLH6lI0ut+nSrN27fPM9iubAKMiQyaK+WbVk+nXDFK9HNzX7ewrMGbCBUq3H5Xx7z0CRmBqFFOWCcX2FP6ggGHbUGbcqGnYPK0qyzD1yiUW7orCtehsT+cudKE6IzTOSszW7RSJpgEjJgdy4pKTIX6+ks6iCunFobXt2k+PjU5Yy7fEUa3gqzrSnopzhKbNF3MGVeklEPlNWheubUfRcZp4nGI1zJ3Kl+vgZhvE0T85BZkVgexnCX9ZwxAYVTXNSMHg7uSKaUCmVhBSKNcAWWUE23JL7eEVUCEeig84D8Q6OeF8eJ1tDOMpSRDlXcgURHXNMhJ64WAhgEEgqpvAFW/txQePoGW/Mk2KCpgSVF3G+fpqOGmbvSRrh10TYhvrdIhbNw2MuARbH8f73M=
